[release]
workspace = true
publish = false              # 不发 crates.io
push = false                 # 不 git push
tag = false                  # 不打 tag
disable-publish-check = true # 不去 crates.io 检查
consolidate-commits = false
consolidate-pushes = false
clean = false                # 不强制 clean
allow-branch = ["main"]
