[package]
name = "mcp-client-rust"
version = "0.1.1"
edition = "2024"
license = "MIT"
repository = "https://github.com/arthasyou/mcp-rs"
description = "Client for the Model Context Protocol (MCP) using HTTP and SSE"

[dependencies]
mcp-core-rs = { version = "0.1.0" }
mcp-error-rs = { version = "0.1.0" }

tower-service = "0.3"
tracing = { version = "0.1", features = ["std"] }
serde_json = "1"
futures = "0.3"
once_cell = "1"
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }
eventsource-client = "0.15"
url = "2"
service_utils_rs = { version = "0.3.20", features = ["request"] }
tokio-util = { version = "0.7", features = ["io"] }
